FROM python:3.13-slim-bookworm

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Install UV
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Set the working directory to /app

# Copy the UV configuration files and install dependencies
COPY uv.lock pyproject.toml requirements.txt ./
RUN uv pip install --system --no-cache --requirements requirements.txt

# Copy the application code from host machine to the container
# Host machine: Your own PC / where the code live

# Expose the port 8000 to the outside world

# Set environment variables for server configuration
ENV WEB_SERVER_RELOAD=true
ENV PYTHONPATH /app

# Set the workdir to the folder containing the API entrypoint

# Start the application through main.py using UV either using CMD or ENTRYPOINT

